#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
测试 Tool.get_expanded_tools() 方法

验证 @tool_action 装饰器与 expandable 工具的自动展开机制：
- 非 expandable 工具返回 None
- expandable 工具自动生成 AutoGeneratedTool 子工具
- 自动解析方法签名、参数类型、docstring 描述
- 生成的子工具可正常执行和转换为 OpenAI schema
- ToolRegistry 注册时自动展开
"""

import os
import sys
import importlib.util

CURRENT_DIR = os.path.dirname(__file__)
PROJECT_ROOT = os.path.dirname(CURRENT_DIR)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from typing import Dict, Any, List


def _load_module(name: str, filepath: str):
    """直接加载单个 .py 文件，避免触发 tools/__init__.py 的全量导入"""
    spec = importlib.util.spec_from_file_location(name, filepath)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


_base_mod = _load_module("tools.base", os.path.join(PROJECT_ROOT, "tools", "base.py"))
_registry_mod = _load_module("tools.registry", os.path.join(PROJECT_ROOT, "tools", "registry.py"))

Tool = _base_mod.Tool
ToolParameter = _base_mod.ToolParameter
tool_action = _base_mod.tool_action
ToolRegistry = _registry_mod.ToolRegistry


# ---- 测试用的 Mock 工具 ----

class NonExpandableTool(Tool):
    """不可展开的普通工具"""

    def __init__(self):
        super().__init__(name="plain_tool", description="普通工具", expandable=False)

    def run(self, parameters: Dict[str, Any]) -> str:
        return "ok"

    def get_parameters(self) -> List[ToolParameter]:
        return []


class ExpandableToolNoActions(Tool):
    """标记为 expandable 但没有 @tool_action 方法"""

    def __init__(self):
        super().__init__(name="empty_expand", description="无 action 的可展开工具", expandable=True)

    def run(self, parameters: Dict[str, Any]) -> str:
        return "ok"

    def get_parameters(self) -> List[ToolParameter]:
        return []


class ExpandableToolWithActions(Tool):
    """标记为 expandable 且拥有多个 @tool_action 方法"""

    def __init__(self):
        super().__init__(name="multi", description="多操作可展开工具", expandable=True)

    def run(self, parameters: Dict[str, Any]) -> str:
        return "dispatch"

    def get_parameters(self) -> List[ToolParameter]:
        return []

    @tool_action("multi_greet", "向用户打招呼")
    def _greet(self, name: str) -> str:
        """打招呼

        Args:
            name: 用户名称
        """
        return f"你好, {name}!"

    @tool_action("multi_add", "两个整数相加")
    def _add(self, a: int, b: int) -> str:
        """整数加法

        Args:
            a: 第一个加数
            b: 第二个加数
        """
        return str(int(a) + int(b))

    @tool_action(None, None)
    def _auto_named(self, text: str = "default") -> str:
        """自动命名的操作

        Args:
            text: 文本内容
        """
        return text


class ExpandableToolMinimalDocstring(Tool):
    """expandable 工具，action 方法没有完整 docstring"""

    def __init__(self):
        super().__init__(name="minimal", description="最小文档工具", expandable=True)

    def run(self, parameters: Dict[str, Any]) -> str:
        return "ok"

    def get_parameters(self) -> List[ToolParameter]:
        return []

    @tool_action("minimal_op", "简单操作")
    def _op(self, x: float, flag: bool = False) -> str:
        return str(x)


# ---- 测试函数 ----

def test_non_expandable_returns_none():
    """非 expandable 工具应返回 None"""
    tool = NonExpandableTool()
    result = tool.get_expanded_tools()
    assert result is None, f"期望 None，实际 {result}"
    print("✅ 非 expandable 工具正确返回 None")


def test_expandable_no_actions_returns_none():
    """expandable 但无 @tool_action 方法，应返回 None"""
    tool = ExpandableToolNoActions()
    result = tool.get_expanded_tools()
    assert result is None, f"期望 None，实际 {result}"
    print("✅ expandable 无 action 正确返回 None")


def test_expanded_tools_count():
    """展开后应生成正确数量的子工具"""
    tool = ExpandableToolWithActions()
    expanded = tool.get_expanded_tools()
    assert expanded is not None, "期望返回列表，实际 None"
    assert len(expanded) == 3, f"期望 3 个子工具，实际 {len(expanded)}"
    print(f"✅ 展开得到 {len(expanded)} 个子工具")


def test_expanded_tool_names():
    """验证展开后工具的名称"""
    tool = ExpandableToolWithActions()
    expanded = tool.get_expanded_tools()
    names = {t.name for t in expanded}

    assert "multi_greet" in names, f"缺少 multi_greet，实际 {names}"
    assert "multi_add" in names, f"缺少 multi_add，实际 {names}"
    # name=None 时应自动生成 parent_name + method_name（去掉前缀下划线）
    assert "multi_auto_named" in names, f"缺少 multi_auto_named，实际 {names}"
    print(f"✅ 子工具名称正确: {sorted(names)}")


def test_expanded_tool_descriptions():
    """验证展开后工具的描述"""
    tool = ExpandableToolWithActions()
    expanded = tool.get_expanded_tools()
    desc_map = {t.name: t.description for t in expanded}

    assert desc_map["multi_greet"] == "向用户打招呼"
    assert desc_map["multi_add"] == "两个整数相加"
    # description=None 时应从 docstring 第一行提取
    assert desc_map["multi_auto_named"] == "自动命名的操作"
    print("✅ 子工具描述正确")


def test_expanded_tool_parameters():
    """验证自动解析的参数信息"""
    tool = ExpandableToolWithActions()
    expanded = tool.get_expanded_tools()
    by_name = {t.name: t for t in expanded}

    # multi_greet 应有 1 个必需参数 name: string
    greet_params = by_name["multi_greet"].get_parameters()
    assert len(greet_params) == 1
    assert greet_params[0].name == "name"
    assert greet_params[0].type == "string"
    assert greet_params[0].required is True
    print("  ✅ multi_greet 参数解析正确")

    # multi_add 应有 2 个必需参数 a, b: integer
    add_params = by_name["multi_add"].get_parameters()
    assert len(add_params) == 2
    param_names = [p.name for p in add_params]
    assert "a" in param_names and "b" in param_names
    for p in add_params:
        assert p.type == "integer"
        assert p.required is True
    print("  ✅ multi_add 参数解析正确")

    # multi_auto_named 应有 1 个可选参数 text: string, default="default"
    auto_params = by_name["multi_auto_named"].get_parameters()
    assert len(auto_params) == 1
    assert auto_params[0].name == "text"
    assert auto_params[0].type == "string"
    assert auto_params[0].required is False
    assert auto_params[0].default == "default"
    print("  ✅ multi_auto_named 参数解析正确（含默认值）")


def test_expanded_tool_run():
    """验证展开后的子工具可以正常执行"""
    tool = ExpandableToolWithActions()
    expanded = tool.get_expanded_tools()
    by_name = {t.name: t for t in expanded}

    result = by_name["multi_greet"].run({"name": "灵夜"})
    assert result == "你好, 灵夜!", f"期望 '你好, 灵夜!'，实际 '{result}'"
    print("  ✅ multi_greet 执行结果正确")

    result = by_name["multi_add"].run({"a": 3, "b": 7})
    assert result == "10", f"期望 '10'，实际 '{result}'"
    print("  ✅ multi_add 执行结果正确")

    result = by_name["multi_auto_named"].run({"text": "hello"})
    assert result == "hello", f"期望 'hello'，实际 '{result}'"
    print("  ✅ multi_auto_named 执行结果正确")

    result = by_name["multi_auto_named"].run({})
    assert result == "default", f"期望 'default'，实际 '{result}'"
    print("  ✅ multi_auto_named 默认值执行正确")


def test_expanded_tool_openai_schema():
    """验证展开后的子工具能正确生成 OpenAI schema"""
    tool = ExpandableToolWithActions()
    expanded = tool.get_expanded_tools()
    by_name = {t.name: t for t in expanded}

    schema = by_name["multi_add"].to_openai_schema()
    assert schema["type"] == "function"
    func_def = schema["function"]
    assert func_def["name"] == "multi_add"
    assert func_def["description"] == "两个整数相加"

    props = func_def["parameters"]["properties"]
    assert "a" in props and "b" in props
    assert props["a"]["type"] == "integer"
    assert set(func_def["parameters"]["required"]) == {"a", "b"}
    print("✅ OpenAI schema 生成正确")


def test_expanded_tool_param_descriptions_from_docstring():
    """验证从 docstring Args 部分提取的参数描述"""
    tool = ExpandableToolWithActions()
    expanded = tool.get_expanded_tools()
    by_name = {t.name: t for t in expanded}

    greet_params = by_name["multi_greet"].get_parameters()
    assert greet_params[0].description == "用户名称", \
        f"期望 '用户名称'，实际 '{greet_params[0].description}'"

    add_params = by_name["multi_add"].get_parameters()
    add_desc = {p.name: p.description for p in add_params}
    assert add_desc["a"] == "第一个加数"
    assert add_desc["b"] == "第二个加数"
    print("✅ docstring 参数描述提取正确")


def test_minimal_docstring_tool():
    """没有完整 docstring 的 action 也应正确展开"""
    tool = ExpandableToolMinimalDocstring()
    expanded = tool.get_expanded_tools()
    assert expanded is not None and len(expanded) == 1
    sub = expanded[0]
    assert sub.name == "minimal_op"
    assert sub.description == "简单操作"

    params = sub.get_parameters()
    assert len(params) == 2
    param_map = {p.name: p for p in params}
    assert param_map["x"].type == "number"
    assert param_map["x"].required is True
    assert param_map["flag"].type == "boolean"
    assert param_map["flag"].required is False
    assert param_map["flag"].default is False
    print("✅ 最小 docstring 工具展开正确（含 float/bool 类型映射）")


def test_registry_auto_expand():
    """验证 ToolRegistry 注册时自动展开"""
    registry = ToolRegistry()
    tool = ExpandableToolWithActions()

    registry.register_tool(tool, auto_expand=True)

    tool_names = registry.list_tools()
    assert "multi_greet" in tool_names, f"注册表中缺少 multi_greet: {tool_names}"
    assert "multi_add" in tool_names, f"注册表中缺少 multi_add: {tool_names}"
    assert "multi_auto_named" in tool_names, f"注册表中缺少 multi_auto_named: {tool_names}"
    # 父工具本身不应被注册
    assert "multi" not in tool_names, f"父工具 multi 不应出现在注册表中: {tool_names}"
    print("✅ ToolRegistry 自动展开注册正确")

    greet_tool = registry.get_tool("multi_greet")
    assert greet_tool is not None, "应能通过 get_tool 获取展开后的子工具"
    result = greet_tool.run({"name": "测试用户"})
    assert "你好" in result and "测试用户" in result, f"执行结果异常: {result}"
    print("✅ 通过注册表获取并执行展开后工具正常")


def test_registry_no_expand():
    """验证 auto_expand=False 时不展开"""
    registry = ToolRegistry()
    tool = ExpandableToolWithActions()

    registry.register_tool(tool, auto_expand=False)

    tool_names = registry.list_tools()
    assert "multi" in tool_names, f"注册表中应包含 multi: {tool_names}"
    assert "multi_greet" not in tool_names, f"不应展开: {tool_names}"
    print("✅ auto_expand=False 时正确不展开")


def main():
    print("🚀 测试 Tool.get_expanded_tools()")
    print("=" * 60)

    tests = [
        test_non_expandable_returns_none,
        test_expandable_no_actions_returns_none,
        test_expanded_tools_count,
        test_expanded_tool_names,
        test_expanded_tool_descriptions,
        test_expanded_tool_parameters,
        test_expanded_tool_run,
        test_expanded_tool_openai_schema,
        test_expanded_tool_param_descriptions_from_docstring,
        test_minimal_docstring_tool,
        test_registry_auto_expand,
        test_registry_no_expand,
    ]

    passed = 0
    failed = 0

    for test_fn in tests:
        print(f"\n--- {test_fn.__doc__} ---")
        try:
            test_fn()
            passed += 1
        except Exception as e:
            failed += 1
            print(f"❌ 失败: {e}")
            import traceback
            traceback.print_exc()

    print("\n" + "=" * 60)
    print(f"🏁 测试完成: {passed} 通过, {failed} 失败, 共 {len(tests)} 个")
    print("=" * 60)


if __name__ == "__main__":
    main()
